# PB — Output boundary: nothing personal and nothing credential-shaped is
# released. The template's stated invariant, in both directions:
#
#  (1) Inbound (TestNoPersonalDataInReport): personal-data shapes are
#      rewritten out of caller text at the request boundary, so the report is
#      synthesized only from already-stripped material and an injected
#      identification number, e-mail or telephone number cannot surface in
#      the rendered report. Proven end to end through a real invocation.
#
#  (2) Outbound (TestOutputGate): PostProcessNode refuses to release content
#      matching a credential shape or a personal-data shape, clearing every
#      output-bearing field as it blocks — the framework's own envelope falls
#      back to the ungated report otherwise.
#
# Deterministic — no model, no network. framework.* / src.* imports only.

import json


from framework.schemas.agent_status import AgentStatus
from framework.schemas.invocation_context import InvocationContext

from src.graph.graph import Graph
from src.nodes.post_process_node import PostProcessNode


# Simulated resident-PII tokens — NOT real data.
_MY_NUMBER = "1234-5678-9012"
_EMAIL = "resident.taro@example.com"
_PHONE = "03-9876-5432"

# Payload with resident PII embedded both in free-text and in PII-named fields.
_PAYLOAD_WITH_PII = json.dumps(
    {
        "report_type": "incident",
        "subject": "Resident complaint follow-up",
        "period": "2025-05",
        "department": "Citizen Affairs",
        "fields": {
            "applicant_name": "Yamada Hanako",
            "address": "1-2-3 Chiyoda, Tokyo",
            "background": f"Filed by resident, My Number {_MY_NUMBER}, contact {_EMAIL}.",
            "findings": f"Callback attempted to {_PHONE}; unresolved.",
        },
        "data_points": [{"case_age_days": 14}],
    },
    ensure_ascii=False,
)


def _run(user_input: str) -> dict:
    # Fully-trusted internal context — the backbone trust gate denies ANONYMOUS.
    ctx = InvocationContext.for_internal(caller_id="test-suite")
    return Graph().invoke(user_input, ctx=ctx)


class TestNoPersonalDataInReport:
    """The rendered report carries no injected personal-data token."""

    def test_run_succeeds(self):
        result = _run(_PAYLOAD_WITH_PII)
        assert (
            result.get("status") == AgentStatus.SUCCESS.value
        ), f"Expected success, got {result.get('status')}. result={result!r}"

    def test_my_number_not_in_report(self):
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert _MY_NUMBER not in report, "My Number token leaked into the report"

    def test_email_not_in_report(self):
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert _EMAIL not in report, "Resident e-mail leaked into the report"

    def test_phone_not_in_report(self):
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert _PHONE not in report, "Resident phone number leaked into the report"

    def test_pii_field_values_redacted_in_report(self):
        """applicant_name / address are PII-keyed → redacted, never rendered raw."""
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert "Yamada Hanako" not in report, "Resident name leaked into the report"
        assert "1-2-3 Chiyoda, Tokyo" not in report, "Resident address leaked into the report"

    def test_report_still_non_empty(self):
        """Stripping PII must not blank the report — the structure survives."""
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert report.strip()
        # The redaction marker is the visible evidence the strip ran.
        assert "[REDACTED]" in report


# Simulated credential patterns — NOT real credentials.
_SIMULATED_API_KEY = "sk-TESTKEY1234567890abcdefghijklmn"
_SIMULATED_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
_SIMULATED_BEARER = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
_SIMULATED_CRED_STR = "password=super_secret_password_abc123"

# A clean, ministry-style report (no credential strings) — must pass the gate.
_CLEAN_REPORT = """\
# Administrative Report — Road Maintenance FY2025

**Report Type:** general
**Subject:** Road Maintenance FY2025
**Reporting Period:** 2025
**Issuing Department:** Public Works

---

## Summary

FY2025 road maintenance proceeded on schedule across all wards.

## Findings

No major incidents. Two sections require resurfacing in Q3.

---

*Generated by the GOV-C2-007 Administrative Report Generator. Prepared under \
APPI (個人情報保護法): no resident personal data is stored or reproduced in this \
report.*
"""


class TestOutputGate:
    """PostProcessNode refuses to release credential-like content.

    Drives PostProcessNode directly, since it owns the output boundary. An
    injected secret in state["result"] must yield an error status and a fixed
    notice for BOTH formatted_output and result — the raw secret must never
    survive into the surfaced output.
    """

    def test_api_key_in_result_is_blocked(self):
        report_with_key = "# Administrative Report\n\n## Notes\n" f"<!-- debug: api_key={_SIMULATED_API_KEY} -->\n"
        result = PostProcessNode().execute({"result": report_with_key})
        assert result.get("status") == AgentStatus.ERROR.value, (
            f"Expected the output to be blocked, got {result.get('status')}. "
            f"formatted_output snippet: {str(result.get('formatted_output',''))[:80]!r}"
        )

    def test_api_key_not_in_output_after_block(self):
        report_with_key = "# Administrative Report\n\n## Notes\n" f"<!-- debug: api_key={_SIMULATED_API_KEY} -->\n"
        result = PostProcessNode().execute({"result": report_with_key})
        # Gate BOTH surfaced fields.
        assert _SIMULATED_API_KEY not in result.get(
            "formatted_output", ""
        ), "Simulated API key leaked into formatted_output"
        assert _SIMULATED_API_KEY not in result.get("result", ""), "Simulated API key leaked into result"

    def test_blocked_output_is_sanitised_stub(self):
        report_with_key = "# Administrative Report\n\n## Notes\n" f"<!-- debug: api_key={_SIMULATED_API_KEY} -->\n"
        result = PostProcessNode().execute({"result": report_with_key})
        # Both surfaced fields carry the sanitised stub marker.
        for field in ("formatted_output", "result"):
            output = result.get(field, "")
            assert "blocked" in output.lower(), f"Expected the fixed blocked notice in {field}, got: {output[:200]!r}"
        assert result.get("error_log"), "Blocked output must carry an error_log entry"

    def test_credential_assignment_in_result_is_blocked(self):
        report_with_cred = "# Administrative Report\n\n## Config\n" f"Internal note: {_SIMULATED_CRED_STR}\n"
        result = PostProcessNode().execute({"result": report_with_cred})
        assert (
            result.get("status") == AgentStatus.ERROR.value
        ), f"A credential assignment must be blocked, got {result.get('status')}"
        assert _SIMULATED_CRED_STR not in result.get("formatted_output", "")
        assert _SIMULATED_CRED_STR not in result.get("result", "")

    def test_jwt_in_result_is_blocked(self):
        report_with_jwt = "# Administrative Report\n\n## Notes\n" f"Token observed: {_SIMULATED_JWT}\n"
        result = PostProcessNode().execute({"result": report_with_jwt})
        assert (
            result.get("status") == AgentStatus.ERROR.value
        ), f"A token pattern must be blocked, got {result.get('status')}"

    def test_bearer_token_in_result_is_blocked(self):
        report_with_bearer = "# Administrative Report\n\n## Notes\n" f"Authorization: {_SIMULATED_BEARER}\n"
        result = PostProcessNode().execute({"result": report_with_bearer})
        assert (
            result.get("status") == AgentStatus.ERROR.value
        ), f"A bearer token must be blocked, got {result.get('status')}"

    def test_clean_report_passes_s3_gate(self):
        """A clean report must NOT trip the gate (success, unchanged)."""
        result = PostProcessNode().execute({"result": _CLEAN_REPORT})
        assert result.get("status") == AgentStatus.SUCCESS.value, (
            f"A clean report must pass the output gate, got {result.get('status')}. "
            f"error_log: {result.get('error_log')}"
        )
        assert (
            result.get("formatted_output") == _CLEAN_REPORT
        ), "Clean report must pass through formatted_output unchanged"
