"""AgentCore Platform v1.0"""

# GOV-C2-007 — ReportRenderingNode
# Domain step 5 (terminal): assemble the drafted sections into the final
# structured administrative report.
#
# The report is rendered through a Jinja2 template when one is configured and
# readable, and through an equivalent built-in layout otherwise, so the agent
# produces the same report whether or not a deployment ships its own template.
#
# The rendered report carries only the sanitized drafts and the section
# structure — no raw resident data.
#
# Wired by the inner graph (DomainWorkflowGraph).
# Returns only changed state keys (partial dict).

import logging
import os
from datetime import datetime, timezone
from typing import Any, ClassVar, Dict, List, Optional

from framework.nodes.function_node import FunctionNode
from framework.schemas.agent_state import AgentState
from framework.schemas.agent_status import AgentStatus
from framework.schemas.trust_level import TrustLevel
from shared.utils.audit_logger import emit_trace_event
from src.schemas.state import from_json

logger = logging.getLogger(__name__)

_DEFAULT_TEMPLATE_PATH = "config/admin_report_template.md"

# Built-in layout, used when no template file is configured or the configured
# one cannot be read.
_BUILTIN_TEMPLATE = """\
# {{ title }}

**Report Type:** {{ report_type }}
**Subject:** {{ subject }}
**Reporting Period:** {{ period }}
**Issuing Department:** {{ department }}
**Generated:** {{ generated_at }}

---

{% for section in sections %}
## {{ section.title }}

{{ section.body }}

{% endfor %}
---

*Generated by the GOV-C2-007 Administrative Report Generator. Prepared under \
APPI (個人情報保護法): no resident personal data is stored or reproduced in this \
report.*
"""

_CLOSING_NOTE = (
    "*Generated by the GOV-C2-007 Administrative Report Generator. Prepared "
    "under APPI (個人情報保護法): no resident personal data is stored or "
    "reproduced in this report.*"
)


def _render_with_jinja2(template_str: str, context: Dict[str, Any]) -> Optional[str]:
    """Render the template with Jinja2 when it is installed, else None."""
    try:
        from jinja2 import Environment, StrictUndefined  # type: ignore[import-not-found]

        env = Environment(undefined=StrictUndefined)
        tmpl = env.from_string(template_str)
        rendered: str = tmpl.render(**context)
        return rendered
    except ImportError:
        logger.debug("Jinja2 is not installed — using the built-in layout")
        return None
    except Exception as exc:
        logger.warning("Template render failed: %s — using the built-in layout", exc)
        return None


def _simple_render(context: Dict[str, Any]) -> str:
    """Deterministic renderer used when Jinja2 is not available."""
    lines: List[str] = []
    lines.append(f"# {context.get('title', 'Administrative Report')}")
    lines.append("")
    lines.append(f"**Report Type:** {context.get('report_type', '')}")
    lines.append(f"**Subject:** {context.get('subject', '')}")
    lines.append(f"**Reporting Period:** {context.get('period', '')}")
    lines.append(f"**Issuing Department:** {context.get('department', '')}")
    lines.append(f"**Generated:** {context.get('generated_at', '')}")
    lines.append("")
    lines.append("---")
    lines.append("")
    for section in context.get("sections", []):
        lines.append(f"## {section.get('title', '')}")
        lines.append("")
        lines.append(str(section.get("body", "")))
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(_CLOSING_NOTE)
    return "\n".join(lines)


def _load_template(template_path: str) -> str:
    """Load the report template from disk, falling back to the built-in layout."""
    if not template_path:
        return _BUILTIN_TEMPLATE
    candidate_paths = [
        template_path,
        os.path.join(os.path.dirname(__file__), "..", "..", template_path),
    ]
    for path in candidate_paths:
        abs_path = os.path.abspath(path)
        if os.path.isfile(abs_path):
            try:
                with open(abs_path, encoding="utf-8") as handle:
                    return handle.read()
            except OSError as exc:
                logger.warning("Could not read the report template at %s: %s", abs_path, exc)
    logger.info("No report template file at %s — using the built-in layout", template_path)
    return _BUILTIN_TEMPLATE


class ReportRenderingNode(FunctionNode):
    """Render the final structured administrative report.

    Input state keys:
        section_drafts: drafted prose per section (from ReportDraftingNode)
        section_plan:   ordered sections and titles (from SectionPlanningNode)
        case_record:    header metadata (report_type, subject, period, department)
        report_config:  live settings seeded from config/config.yaml

    Output state keys (partial dict):
        administrative_report: the rendered report
        status:                SUCCESS
    """

    # The manifest's declared caller level. The request boundary
    # (PreProcessNode) refuses anything below it before this node is
    # reachable, so this is defence in depth rather than the primary gate —
    # and declaring a HIGHER level here would refuse the declared caller and
    # make the public path unreachable.
    required_trust_level: ClassVar[TrustLevel] = TrustLevel.VERIFIED_EXTERNAL

    def execute(self, state: AgentState) -> Dict[str, Any]:
        section_drafts: Dict[str, str] = from_json(state.get("section_drafts"), {}) or {}
        section_plan: List[Dict[str, Any]] = from_json(state.get("section_plan"), []) or []
        case_record: Dict[str, Any] = from_json(state.get("case_record"), {}) or {}
        report_config: Dict[str, Any] = from_json(state.get("report_config"), {}) or {}

        configured_path = report_config.get("report_template_path")
        template_path = configured_path if isinstance(configured_path, str) else _DEFAULT_TEMPLATE_PATH

        subject = str(case_record.get("subject", ""))
        report_type = str(case_record.get("report_type", "general"))

        # Build the ordered (title, body) section list from the plan and drafts.
        rendered_sections: List[Dict[str, str]] = []
        for section in section_plan:
            key = str(section.get("key", ""))
            body = section_drafts.get(key, "")
            if not body and not section.get("required", True):
                continue
            rendered_sections.append(
                {
                    "title": section.get("title", str(key).replace("_", " ").title()),
                    "body": body or "(No content available for this section.)",
                }
            )

        title = f"Administrative Report — {subject}" if subject else "Administrative Report"

        render_context: Dict[str, Any] = {
            "title": title,
            "report_type": report_type,
            "subject": subject,
            "period": str(case_record.get("period", "")),
            "department": str(case_record.get("department", "")),
            "generated_at": datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            "sections": rendered_sections,
        }

        template_str = _load_template(template_path)
        administrative_report = _render_with_jinja2(template_str, render_context)
        if administrative_report is None:
            administrative_report = _simple_render(render_context)

        emit_trace_event(
            "administrative_report_rendered",
            {
                "report_type": report_type,
                "section_count": len(rendered_sections),
                "report_chars": len(administrative_report),
            },
            state,
        )

        logger.info(
            "ReportRenderingNode: rendered report (%d chars, %d sections)",
            len(administrative_report),
            len(rendered_sections),
        )

        return {
            "administrative_report": administrative_report,
            "status": AgentStatus.SUCCESS.value,
        }
